/*
 * game/data.c -- Carga de dados ROM->RAM e estado global do jogo
 *
 * Fase 1: leitura real dos bin?rios gerados por pack_data.py e
 * embebidos na ROM pelo rescomp (teams_data[], coaches_data[]).
 *
 * Layout bin?rio de teams.bin (big-endian):
 *   [0..1]  u16 team_count        = 29
 *   [2..3]  u16 players_per_team  = 16
 *   Por equipe (offset 4 + t?410):
 *     TeamRecord [26 bytes]:
 *       [+0..+19]  char name[20]   NUL-terminated ASCII
 *       [+20]      u8  n1
 *       [+21]      u8  n2
 *       [+22..+24] char nac[3]     ex "POR" (sem NUL)
 *       [+25]      u8  _pad
 *     PlayerRecord [24 bytes] ? 16, imediatamente ap?s:
 *       [+0..+15]  char name[16]   NUL-terminated ASCII
 *       [+16]      u8  pos         0=GR 1=DF 2=MD 3=AV
 *       [+17..+19] char nac[3]     ex "POR"
 *       [+20..+23] u8  _pad[4]
 *
 * Layout bin?rio de coaches.bin:
 *   [0..1]  u16 coach_count = 50
 *   Por coach (offset 2 + c?20):
 *     CoachRecord [20 bytes]: char name[20] NUL-terminated ASCII
 *
 * Strength inicial dos jogadores:
 *   base = 75 - n2_equipe * 3   (n2=0 forte, n2=15 fraco)
 *   strength = clamp(base + rng_range(20) - 10, 20, 99)
 *
 * Salary inicial: strength * 150L escudos/m?s.
 */

#include <genesis.h>
#include "data.h"
#include "types.h"
#include "../engine/rng.h"
#include "../engine/compat.h"

/* res/resources.h gerado automaticamente pelo rescomp.
 * Declara: extern const u8 teams_data[];
 *          extern const u8 coaches_data[];
 *          extern const TileSet font_tiles; */
/* res/resources.h is generated by rescomp from res/resources.res
 * Run: rescomp res/resources.res  (done automatically by makefile.gen)
 * Declares: extern const u8 teams_data[];
 *           extern const u8 coaches_data[];
 *           extern const TileSet font_tiles;               */
#include "../../res/resources.h"

/* ------------------------------------------------------------------ */
/* Constantes de layout bin?rio (mirror de pack_data.py)              */
/* ------------------------------------------------------------------ */

#define BIN_TEAM_NAME_LEN    20u
#define BIN_PLAYER_NAME_LEN  16u
#define BIN_COACH_NAME_LEN   20u
#define BIN_PLAYER_REC_SIZE  24u
#define BIN_TEAM_REC_SIZE    26u
#define BIN_TEAM_BLOCK_SIZE  (BIN_TEAM_REC_SIZE + PLAYERS_PER_TEAM * BIN_PLAYER_REC_SIZE)
#define BIN_TEAMS_HDR_SIZE    4u
#define BIN_COACHES_HDR_SIZE  2u
#define BIN_COACH_REC_SIZE   20u

static u8 nat_from_code(const u8 *c) {
    if (c[0]=='P'&&c[1]=='O'&&c[2]=='R') return 0u;
    if (c[0]=='B'&&c[1]=='R'&&c[2]=='A') return 1u;
    if (c[0]=='A'&&c[1]=='R'&&c[2]=='G') return 2u;
    if (c[0]=='E'&&c[1]=='S'&&c[2]=='P') return 3u;
    if (c[0]=='I'&&c[1]=='N'&&c[2]=='G') return 4u;
    if (c[0]=='F'&&c[1]=='R'&&c[2]=='A') return 5u;
    if (c[0]=='I'&&c[1]=='T'&&c[2]=='A') return 6u;
    if (c[0]=='A'&&c[1]=='L'&&c[2]=='E') return 7u;
    if (c[0]=='S'&&c[1]=='E'&&c[2]=='R') return 8u;
    if (c[0]=='J'&&c[1]=='U'&&c[2]=='G') return 8u;
    if (c[0]=='C'&&c[1]=='R'&&c[2]=='O') return 9u;
    return 0u;
}

static void copy_name(char *dst, const u8 *src, u8 dst_len) {
    u8 i;
    for (i = 0u; i < (u8)(dst_len - 1u); i++) {
        if (src[i] == 0u) break;
        dst[i] = (char)src[i];
    }
    dst[i] = '\0';
}

/* ------------------------------------------------------------------ */
/* Arrays globais                                                      */
/* ------------------------------------------------------------------ */

Player       g_players[TEAM_COUNT * PLAYERS_PER_TEAM];
Team         g_teams[TEAM_COUNT];
char         g_coaches[COACH_COUNT][COACH_NAME_LEN];
MatchResult  g_results[200];
CupTie       g_cup_ties[16];
SeasonRecord g_palmares[PALMARES_COUNT];

u8   g_season_num      = 1u;
u8   g_round           = 0u;
u8   g_player_team_idx = 0u;
u8   g_division        = 0u;
long g_money           = 0L;
u8   g_results_count   = 0u;
u8   g_cup_ties_count  = 0u;
u8   g_cup_phase       = 0u;

/* ------------------------------------------------------------------ */
/* data_init()                                                         */
/* ------------------------------------------------------------------ */

void data_init(void) {
    u8        t, p, c, i;
    u16       player_idx = 0u;
    const u8 *ptr;
    u16       file_team_count, file_players_per_team, file_coach_count;

    /* 1. coaches ---------------------------------------------------- */
    ptr              = coaches_data;
    file_coach_count = ((u16)ptr[0] << 8) | (u16)ptr[1];
    ptr             += BIN_COACHES_HDR_SIZE;
    if (file_coach_count > (u16)COACH_COUNT) file_coach_count = (u16)COACH_COUNT;
    for (c = 0u; c < (u8)file_coach_count; c++) {
        copy_name(g_coaches[c], ptr, (u8)COACH_NAME_LEN);
        ptr += BIN_COACH_REC_SIZE;
    }
    for (c = (u8)file_coach_count; c < (u8)COACH_COUNT; c++) g_coaches[c][0] = '\0';

    /* 2. teams + players ------------------------------------------- */
    ptr                   = teams_data;
    file_team_count       = ((u16)ptr[0] << 8) | (u16)ptr[1];
    file_players_per_team = ((u16)ptr[2] << 8) | (u16)ptr[3];
    ptr                  += BIN_TEAMS_HDR_SIZE;
    if (file_team_count > (u16)TEAM_COUNT) file_team_count = (u16)TEAM_COUNT;

    for (t = 0u; t < (u8)file_team_count; t++) {
        Team     *team     = &g_teams[t];
        const u8 *team_ptr = ptr;

        copy_name(team->name, team_ptr, (u8)TEAM_NAME_LEN);
        team->n1 = team_ptr[20];
        team->n2 = team_ptr[21];

        team->player_start  = player_idx;
        team->player_count  = (u8)file_players_per_team;
        team->division      = (t < (u8)TEAMS_PER_DIV_1) ? 0u : 1u;
        team->formation     = (u8)FORM_4_4_2;
        team->coach_idx     = (u8)(t % (u8)COACH_COUNT);
        team->wins          = 0u;
        team->draws         = 0u;
        team->losses        = 0u;
        team->goals_for     = 0u;
        team->goals_against = 0u;
        team->points        = 0u;
        team->salary_total  = 0L;
        team->cup_active    = 1u;
        team->money         = 150000L - (long)team->n2 * 8000L;
        if (team->money < 20000L) team->money = 20000L;
        team->stadium_cap   = (u16)(30000u - (u16)team->n2 * 1500u);
        if (team->stadium_cap < 5000u) team->stadium_cap = 5000u;
        team->ticket_price  = 5u;

        ptr = team_ptr + BIN_TEAM_REC_SIZE;
        for (p = 0u; p < (u8)file_players_per_team; p++) {
            Player   *pl   = &g_players[player_idx];
            const u8 *prec = ptr + (u16)p * BIN_PLAYER_REC_SIZE;
            s16 raw;

            copy_name(pl->name, prec, (u8)PLAYER_NAME_LEN);
            pl->pos      = prec[16];
            pl->nat      = nat_from_code(prec + 17u);
            pl->on_field      = (p < 11u) ? 1u : 0u;

            raw = (s16)(75u - (u16)team->n2 * 3u) + (s16)rng_range(20u) - 10;
            if (raw < 20) raw = 20;
            if (raw > 99) raw = 99;
            pl->strength = (u8)raw;

            pl->salary          = (long)pl->strength * 150L;
            team->salary_total += pl->salary;
            player_idx++;
        }
        ptr = team_ptr + BIN_TEAM_BLOCK_SIZE;
    }

    /* 3. palmares --------------------------------------------------- */
    for (i = 0u; i < (u8)PALMARES_COUNT; i++) {
        g_palmares[i].season_num    = 0u;
        g_palmares[i].div1_champion = 0u;
        g_palmares[i].cup_champion  = 0u;
        g_palmares[i].player_div    = 0u;
        g_palmares[i].player_pos    = 0u;
    }

    /* 4. estado inicial --------------------------------------------- */
    g_season_num      = 1u;
    g_round           = 1u;
    g_player_team_idx = 0u;
    g_round           = 1u;
    g_division        = g_teams[0].division;
    g_money           = g_teams[0].money;
    g_results_count   = 0u;
    {
        u16 gi;
        for (gi = 0u; gi < (u16)((u16)TEAM_COUNT * (u16)PLAYERS_PER_TEAM); gi++)
            g_goals[gi] = 0u;
    }
    g_cup_ties_count  = 0u;
    g_cup_phase       = 0u;
}

/* ------------------------------------------------------------------ */
/* data_assign_divisions()                                             */
/* ------------------------------------------------------------------ */

void data_assign_divisions(void) {
    u8 order[TEAM_COUNT], div2_order[TEAM_COUNT];
    u8 count, div2_count;
    u8 i;

    data_sort_standings(0u, order, &count);
    if (count < 3u) return;

    data_sort_standings(1u, div2_order, &div2_count);

    for (i = 0u; i < 3u; i++) {
        g_teams[order[count - 1u - i]].division = 1u;
    }
    for (i = 0u; i < 3u && i < div2_count; i++) {
        g_teams[div2_order[i]].division = 0u;
    }
}

/* ------------------------------------------------------------------ */
/* data_reset_season_stats()                                           */
/* ------------------------------------------------------------------ */

void data_reset_season_stats(void) {
    u8 t;
    for (t = 0u; t < (u8)TEAM_COUNT; t++) {
        g_teams[t].wins = g_teams[t].draws = g_teams[t].losses = 0u;
        g_teams[t].goals_for = g_teams[t].goals_against = 0u;
        g_teams[t].points    = 0u;
        g_teams[t].cup_active = 1u;
    }
    g_results_count = g_cup_ties_count = g_cup_phase = 0u;
}

/* ------------------------------------------------------------------ */
/* data_get_team_player_count() / data_get_team_gk_count()            */
/* ------------------------------------------------------------------ */

u8 data_get_team_player_count(u8 team_idx) {
    if (team_idx >= (u8)TEAM_COUNT) return 0u;
    return g_teams[team_idx].player_count;
}

u8 data_get_team_gk_count(u8 team_idx) {
    u8 count = 0u, i;
    Team *team;
    if (team_idx >= (u8)TEAM_COUNT) return 0u;
    team = &g_teams[team_idx];
    for (i = 0u; i < team->player_count; i++) {
        if (g_players[(u16)team->player_start + i].pos == (u8)POS_GR) count++;
    }
    return count;
}

/* ------------------------------------------------------------------ */
/* data_sort_standings()                                               */
/* ------------------------------------------------------------------ */

void data_sort_standings(u8 div, u8 *out_order, u8 *out_count) {
    u8  buf[TEAM_COUNT];
    u8  n = 0u, t, i, j, tmp, b_wins;
    Team *ta, *tb;
    s16 diff_a, diff_b;

    for (t = 0u; t < (u8)TEAM_COUNT; t++) {
        if (g_teams[t].division == div) buf[n++] = t;
    }

    for (i = 1u; i < n; i++) {
        tmp = buf[i]; j = i;
        while (j > 0u) {
            ta = &g_teams[buf[j-1u]]; tb = &g_teams[tmp];
            diff_a = GOAL_DIFF(ta->goals_for, ta->goals_against);
            diff_b = GOAL_DIFF(tb->goals_for, tb->goals_against);
            b_wins = 0u;
            if (tb->points > ta->points) b_wins = 1u;
            else if (tb->points == ta->points) {
                if      (diff_b > diff_a) b_wins = 1u;
                else if (diff_b == diff_a && tb->goals_for > ta->goals_for) b_wins = 1u;
            }
            if (!b_wins) break;
            buf[j] = buf[j-1u]; j--;
        }
        buf[j] = tmp;
    }
    for (i = 0u; i < n; i++) out_order[i] = buf[i];
    *out_count = n;
}
