/*
 * res/resources.h - AUTO-GENERATED by rescomp
 *
 * DO NOT EDIT - this file is regenerated every build by:
 *   rescomp res/resources.res res/resources.s
 *
 * This placeholder is included for IDE navigation.
 * The real file is generated during the build by makefile.gen.
 *
 * If this file is missing or stale, run:
 *   make data   (regenerates teams.bin and coaches.bin)
 *   make        (runs rescomp + full build)
 *
 * Declarations match res/resources.res:
 *   TILESET font_tiles   "gfx/font_cp850.png"  NONE NONE
 *   BIN     teams_data   "data/teams.bin"       2 2 0 FAST
 *   BIN     coaches_data "data/coaches.bin"     2 2 0 FAST
 */

#ifndef RESOURCES_H
#define RESOURCES_H

#include <genesis.h>

/* Font tileset loaded into VRAM at FONT_BASE_TILE (tile 1) */
extern const TileSet font_tiles;

/* Team + player data - 11894 bytes, big-endian binary */
extern const u8 teams_data[];

/* Coach names - 1002 bytes, big-endian binary */
extern const u8 coaches_data[];

#endif /* RESOURCES_H */
